baseURL = 'https://zimang.fun'
title = 'Zimang Book'
theme = 'hugo-book'

enableGitInfo = true
BookDateFormat = 'January 2, 2006'

[params]
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = 'my2026'
  BookRepo = 'https://github.com/Zimang/zimang.github.io/'
  BookLastChangeLink = '{{ .Site.Params.BookRepo }}/commit/{{ .GitInfo.Hash }}'