[module]
[module.hugoVersion]
  extended = true
  min = "0.146.0"


baseURL = 'https://zimang.fun/my2026'
title = 'Zimang Book'
theme = 'hugo-book'



enableGitInfo = true
BookLastChangeLink = '{{ .Site.Params.BookRepo }}/commit/{{ .GitInfo.Hash }}'
BookDateFormat = 'January 2, 2006'

[params]
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = 'my2026'